# Pandas:


*   Pandas is a Python library used for working with data sets.
*   It has functions for analyzing, cleaning, exploring, and manipulating data.

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#Import pandas library

In [ ]:
import pandas as pd

#Load Dataset

In [ ]:
a = pd.read_csv("/content/WMT_1970-10-01_2025-01-31.csv")

#View top 5 rows in the dataset

In [ ]:
a.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1972-08-25  0.021159  0.021566  0.021159  0.021484   0.011639  7526400.0
1  1972-08-28  0.021484  0.021647  0.021403  0.021403   0.011595  2918400.0
2  1972-08-29  0.021322  0.021322  0.021159  0.021159   0.011463  5836800.0
3  1972-08-30  0.021159  0.021159  0.020996  0.021159   0.011463  1228800.0
4  1972-08-31  0.020996  0.020996  0.020833  0.020833   0.011286  2611200.0

#view bottom 5 rows in the dataset

In [ ]:
a.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
9520,2010-05-20,17.456667,17.653334,17.100000,17.100000,12.519563,81768000.0
9521,2010-05-21,16.910000,17.123333,16.836666,17.123333,12.536645,73645800.0
9522,2010-05-24,17.013332,17.180000,16.966667,17.000000,12.446346,40673400.0
9523,2010-05-25,16.750000,16.833332,16.666668,16.760000,12.270632,72187200.0
9524,2010-05-26,16.786667,NaN,NaN,NaN,NaN,NaN

#To find number of rows and columns presented in the dataset

In [ ]:
a.shape

(9525, 7)

# To find the number of rows in the dataset

In [ ]:
a.shape[0]

9525

# To find the number of columns in the dataset

In [ ]:
a.shape[1]

7

#Complete information about the dataset

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9525 entries, 0 to 9524
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       9525 non-null   object
 1   Open       9525 non-null   float64
 2   High       9524 non-null   float64
 3   Low        9524 non-null   float64
 4   Close      9524 non-null   float64
 5   Adj Close  9524 non-null   float64
 6   Volume     9524 non-null   float64
dtypes: float64(6), object(1)
memory usage: 521.0+ KB

# To find statistical descrption about the numerical cloumns

In [ ]:
a.describe()

,Open,High,Low,Close,Adj Close,Volume
count,9525.000000,9524.000000,9524.000000,9524.000000,9524.000000,9.524000e+03
mean,6.489973,6.564326,6.409137,6.488341,4.290013,2.140893e+07
std,7.373380,7.458596,7.283728,7.372042,4.969113,1.969888e+07
min,0.005208,0.005208,0.004801,0.005208,0.002839,0.000000e+00
25%,0.110352,0.111328,0.109620,0.110677,0.064710,9.376800e+06
50%,3.541667,3.593750,3.500000,3.541667,2.187379,1.701120e+07
75%,15.666667,15.830000,15.450833,15.645833,10.427937,2.721120e+07
max,23.187500,23.416668,22.854168,23.145832,14.910343,3.955008e+08

# Location

In [ ]:
a.iloc[1]

Date         1972-08-28
Open           0.021484
High           0.021647
Low            0.021403
Close          0.021403
Adj Close      0.011595
Volume        2918400.0
Name: 1, dtype: object

In [ ]:
a.loc[1]

Date         1972-08-28
Open           0.021484
High           0.021647
Low            0.021403
Close          0.021403
Adj Close      0.011595
Volume        2918400.0
Name: 1, dtype: object

In [ ]:
a.iloc[1:3]

         Date      Open      High       Low     Close  Adj Close     Volume
1  1972-08-28  0.021484  0.021647  0.021403  0.021403   0.011595  2918400.0
2  1972-08-29  0.021322  0.021322  0.021159  0.021159   0.011463  5836800.0

# To check null values presented in the dataset or not

In [ ]:
a.isna()

       Date   Open   High    Low  Close  Adj Close  Volume
0     False  False  False  False  False      False   False
1     False  False  False  False  False      False   False
2     False  False  False  False  False      False   False
3     False  False  False  False  False      False   False
4     False  False  False  False  False      False   False
...     ...    ...    ...    ...    ...        ...     ...
9520  False  False  False  False  False      False   False
9521  False  False  False  False  False      False   False
9522  False  False  False  False  False      False   False
9523  False  False  False  False  False      False   False
9524  False  False   True   True   True       True    True

[9525 rows x 7 columns]

In [ ]:
a.isna().any()

Date         False
Open         False
High          True
Low           True
Close         True
Adj Close     True
Volume        True
dtype: bool

In [ ]:
a.isnull()

       Date   Open   High    Low  Close  Adj Close  Volume
0     False  False  False  False  False      False   False
1     False  False  False  False  False      False   False
2     False  False  False  False  False      False   False
3     False  False  False  False  False      False   False
4     False  False  False  False  False      False   False
...     ...    ...    ...    ...    ...        ...     ...
9520  False  False  False  False  False      False   False
9521  False  False  False  False  False      False   False
9522  False  False  False  False  False      False   False
9523  False  False  False  False  False      False   False
9524  False  False   True   True   True       True    True

[9525 rows x 7 columns]

In [ ]:
a.isnull().sum()

Date         0
Open         0
High         1
Low          1
Close        1
Adj Close    1
Volume       1
dtype: int64

#To access particular column in a datset

In [ ]:
a[['Volume','Close']].head()

      Volume     Close
0  7526400.0  0.021484
1  2918400.0  0.021403
2  5836800.0  0.021159
3  1228800.0  0.021159
4  2611200.0  0.020833

#Filter

In [ ]:
a[a['Open']>20].head()

,Date,Open,High,Low,Close,Adj Close,Volume
6895,1999-12-10,20.833332,21.500000,20.625000,21.083332,13.571575,37787400.0
6896,1999-12-13,21.833332,23.062500,21.583332,22.666668,14.590783,28173000.0
6897,1999-12-14,22.333332,22.833332,22.312500,22.354168,14.389634,22515300.0
6898,1999-12-15,22.333332,22.354168,21.708332,22.005207,14.175563,23528400.0
6899,1999-12-16,22.250000,22.916668,22.000000,22.875000,14.735876,25461000.0

#Change column name:

In [ ]:
a = a.rename(columns={'volume':'vol'})
a.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

#Identifying outliners using IQR:

In [ ]:
a.isna().sum()

Date         0
Open         0
High         1
Low          1
Close        1
Adj Close    1
Volume       1
dtype: int64

In [ ]:
import numpy as np
a['Volume'].isna().sum()
vol = a['Volume'].dropna()
q1 = vol.quantile(0.25)
q3 = vol.quantile(0.75)
iqr = q3-q1
lower_bound = q1 - (1.5*iqr)
upper_bound = q3 + (1.5*iqr)
outliers = vol[(vol<lower_bound) | (vol>upper_bound)]
print("Outliers:",outliers)

Outliers: 198     149913600.0
555     225945600.0
567      58521600.0
810      81177600.0
869     124339200.0
           ...
9518     96683100.0
9519     61256100.0
9520     81768000.0
9521     73645800.0
9523     72187200.0
Name: Volume, Length: 593, dtype: float64

#Create a new column in past dataset:

In [ ]:
a['dates'] = pd.to_datetime(a['Date']).dt.year.apply(lambda x: 'old' if x <= 1988 else 'new')
print(a[['Date','dates']].tail())

            Date dates
9520  2010-05-20   new
9521  2010-05-21   new
9522  2010-05-24   new
9523  2010-05-25   new
9524  2010-05-26   new

#Groupby and aggregation:

In [ ]:
a_groupby = a.groupby('Date').agg({'Volume':['mean','max','min']})
print(a_groupby.head())

               Volume
                 mean        max        min
Date
1972-08-25  7526400.0  7526400.0  7526400.0
1972-08-28  2918400.0  2918400.0  2918400.0
1972-08-29  5836800.0  5836800.0  5836800.0
1972-08-30  1228800.0  1228800.0  1228800.0
1972-08-31  2611200.0  2611200.0  2611200.0

#pivoting data:

In [ ]:
a_pivot = a.pivot(index='Date',columns='dates',values='Volume')
print(a_pivot)

dates              new        old
Date
1972-08-25         NaN  7526400.0
1972-08-28         NaN  2918400.0
1972-08-29         NaN  5836800.0
1972-08-30         NaN  1228800.0
1972-08-31         NaN  2611200.0
...                ...        ...
2010-05-20  81768000.0        NaN
2010-05-21  73645800.0        NaN
2010-05-24  40673400.0        NaN
2010-05-25  72187200.0        NaN
2010-05-26         NaN        NaN

[9525 rows x 2 columns]

#Memory optimization(Downcasting):

In [ ]:
a['Date']=

#Merging two Datasets:

In [ ]:
a = pd.read_csv("/content/WMT_1970-10-01_2025-01-31.csv")
b = pd.read_csv("/content/features.csv")
c = pd.merge(a,b,on='Date')
print(c.head())

         Date   Open       High        Low      Close  Adj Close    Volume  \
0  2010-02-05  17.59  17.843332  17.586666  17.816668  12.896234  46637400
1  2010-02-05  17.59  17.843332  17.586666  17.816668  12.896234  46637400
2  2010-02-05  17.59  17.843332  17.586666  17.816668  12.896234  46637400
3  2010-02-05  17.59  17.843332  17.586666  17.816668  12.896234  46637400
4  2010-02-05  17.59  17.843332  17.586666  17.816668  12.896234  46637400

   Store  Temperature  Fuel_Price  MarkDown1  MarkDown2  MarkDown3  MarkDown4  \
0      1        42.31       2.572        NaN        NaN        NaN        NaN
1      2        40.19       2.572        NaN        NaN        NaN        NaN
2      3        45.71       2.572        NaN        NaN        NaN        NaN
3      4        43.76       2.598        NaN        NaN        NaN        NaN
4      5        39.70       2.572        NaN        NaN        NaN        NaN

   MarkDown5         CPI  Unemployment  IsHoliday
0        NaN  211.096358         8.106      False
1        NaN  210.752605         8.324      False
2        NaN  214.424881         7.368      False
3        NaN  126.442065         8.623      False
4        NaN  211.653972         6.566      False

In [ ]:
b.isna().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

In [ ]:
b['MarkDown1'].fillna(b['MarkDown1'].mean(),inplace = True)

<ipython-input-48-819cb6fc0a19>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['MarkDown1'].fillna(b['MarkDown1'].mean(),inplace = True)

In [ ]:
b.isna().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1          0
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

Cleaning using where condition:

In [ ]:
b['sales'] = np.where(b['Fuel_Price']>2,'high','low')
print(b[['Fuel_Price','sales']].head())

   Fuel_Price sales
0       2.572  high
1       2.548  high
2       2.514  high
3       2.561  high
4       2.625  high

#seaborn:
*   Seaborn is a statistical data visualization library in Python that builds on Matplotlib and integrates well with pandas data structures.
*   It is commonly used for drawing attractive and informative statistical graphics.
*   It is built on top of Matplotlib and works well with pandas DataFrames.
*   It offers built-in themes and color palettes to improve the aesthetics of visualizations.

In [12]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
a = sns.load_dataset("tips")
print(a.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
print(a.tail())

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [15]:
a.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [16]:
b = sns.load_dataset("titanic")
print(b.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [17]:
print(b.tail())

     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second
887         1       1  female  19.0      0      0  30.00        S   First
888         0       3  female   NaN      1      2  23.45        S   Third
889         1       1    male  26.0      0      0  30.00        C   First
890         0       3    male  32.0      0      0   7.75        Q   Third

       who  adult_male deck  embark_town alive  alone
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

In [18]:
a.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [19]:
#merge both datasets
c = pd.merge(a,b,on='sex')
print(c.head())

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size, survived, pclass, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

[0 rows x 21 columns]